### ISSUE TITLE
 EOSIO SDK for Swift must be 12.0

### ISSUE THREAD

**Issue by PeterCore** [EOSIO/eosio-swift-abieos-serialization-provider#70]
C++ SDK is not supported or iOS SDK is not supported

**Comment by brandonfancher** [comment]
@PeterCore Can you provide more context? We are aware that:

* ABIEOS Serialization Provider (this library) targets iOS 12+
* EOSIO SDK for Swift targets iOS 11+
* Because this is currently the only serialization provider available for EOSIO SDK for Swift, when used in combination with this provider, EOSIO SDK for Swift only supports iOS 12+ in practice

That is mentioned in the EOSIO SDK for Swift README [here](https://github.com/EOSIO/eosio-swift#installation).

Are you requesting support for 11+? Or is there a different issue you are running into?

If there is sufficient demand, we _might_ be able to provide an alternate implementation of the ABIEOS Serialization Provider that supports iOS 11. But we'd have to include a Boost dependency that adds some weight to the package.

**Comment by yaorenjin1986** [comment]
IOS 12 prevents me from using this library

**Comment by PeterCore** [comment]
@brandonfancher thank you

**Comment by gleehokie** [comment]
> IOS 12 prevents me from using this library

@yaorenjin1986 what about iOS 12 is preventing you from using the library?  What version of iOS are you using?

**Comment by mwawrusch** [comment]
Same here. We need iOS 11 support. A common practice on iOS is always supporting the last 2 versions. IOS 13 will launch in fall, unfortunately...

**Comment by brandonfancher** [comment]
Thanks, @mwawrusch. Noted.
